#!/usr/bin/env php
<?php
require __DIR__ . '/vendor/autoload.php';
require_once __DIR__ . '/bootstrap/helpers.php'; // 👈 ajoute ici

define('ROOT', realpath(__DIR__)); // 👈 AJOUTE CECI

use Dotenv\Dotenv;
use Symfony\Component\Console\Application;

$dotenv = Dotenv::createImmutable(__DIR__);
$dotenv->load();

use App\Commands\LangScanCommand;
use App\Commands\MakeControllerCommand;
use App\Commands\MakeModelCommand;
use App\Commands\MakeRepositoryCommand;
use \App\Commands\MakeViewCommand;
use App\Commands\MakeCrudCommand;
use App\Commands\MakeDatabaseCommand;
use App\Commands\MakeMigrationCommand;
use App\Commands\MigrateCommand;
use App\Commands\MigrateFreshCommand;
use App\Commands\MigrateRollbackCommand;
use App\Commands\MigrateSeedCommand;
use App\Commands\ViewCacheCommand;
use App\Commands\MakeComponentCommand;

$app = new Application('Doliprane Console');

$app->add(new LangScanCommand());
$app->add(new MakeControllerCommand());
$app->add(new MakeModelCommand());
$app->add(new MakeRepositoryCommand());
$app->add(new MakeViewCommand());
$app->add(new MakeCrudCommand());
$app->add(new MakeDatabaseCommand());
$app->add(new MakeMigrationCommand());
$app->add(new MigrateCommand());
$app->add(new MigrateFreshCommand());
$app->add(new MigrateRollbackCommand());
$app->add(new MigrateSeedCommand());
$app->add(new ViewCacheCommand());
$app->add(new MakeComponentCommand());

$app->run();
