#!/usr/bin/env php
<?php
require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use App\Commands\LangScanCommand;

$app = new Application('Doliprane CLI');

$app->add(new LangScanCommand());

$app->run();
